### ISSUE TITLE
[FRONTEND] Hybrid python frontend

### ISSUE THREAD

**Issue by were** [dmlc/tvm#1213]
## TODOs
- [x] Summarize the design decision, language, keyword, examples descriptions in docs/dev/hybrid_script.md (reuse what we have in this issue)
- [x] Also cross pasting the issue in here
- [x] Update the PR to support the discussed feature, up to the parse function
- [ ] Write a tutorial on how to use hybrid script under tutorials
- [ ] Support generating of op in a later part of the PR, the first step can redirect to extern op
- [ ] Support scheduling of outer loop nest structures.
- [ ] Write a blogpost introducing this feature.

## Discussion
I have an ongoing PR (#1251 ) which already gives a runnable version of Python subset to HalideIR. Some interfaces and features require refinement.
This frontend is aimed at:
- Building IR in a more intuitive way and providing a more flexible way to describe algorithms
- Writing a preliminary version of some patterns that cannot be depicted in the current tvm interface easily

I will put a tick to the checkbox, if the feature mentioned below is both supported and approved by the disscussion.

## Features
- [x] Software emulation. To define a function, you need to use `tvm.hybrid.script` decorator to indicate this is a hybrid function:
````Python
@tvm.hybrid.script
def foo(arg_list):
    #function body
````
This decorator will help you to import key words spontaneously when calling this function.
Every element in the argument list is either a python variable or `numpy` tensor.
- [x] The current parse interface looks like:
````Python
tvm.hybrid.parse(foo, [args]) # return an ir root of this function
````
- [x] @tqchen and I discussed and want the final interface looks like:
The parse interface is still kept.
````Python
op = foo(*args) #If arguments are tvm tensors, it returns the op node of this function
sch = tvm.create_schedule(op) # You can do some simple schedule operations on it
````
I believe most schedule methods like `split`, `unroll`, `vectorize`, `parallel`, `bind`, and `reorder` (for perfect loops) should be simple enough to support.
- [x] Variables
It takes the first store of a variable as its declaration.
Because there is no variables in `HalideIR`, all the mutatable variables will be lowered to an array with size 1.
Unlike conventional Python, the declared array can only be used in the scope level it is declared.
- [x] Different types of for loops
You can use one of `serial`, `unrolled`, `parallel`, and `vectorized` to annotate the loop type like this:
````Python
for i in unrolled(5):
     a[i] = i
````
which will be unrolled across the lower passes.
- [x] If-then-else statement and select expression
````Python
if condition:
    # do something
a = b if condition else c
````
So far NO `True` and `False` keyword supported
- [x] Math intrinsics: `log`, `exp`, `sigmoid`, `tanh`, `power`, and `popcount`. No import is required, just use it!
- [x] Build specific ops for the node generated by hybrid python frontend
- [ ] Array allocation
**TODO** I want to use a function call `allocation(shape, type, share/local)` to declare an array buffer.
- [x] Thread bind
@kevinthesun suggested this. The current interface is:
````Python
for tx in bind(100, "threadIdx.x"):
    a[tx] = b[tx]
````
However, @tqchen pointed out this is kinda confusing. Some options below:
````Python
for tx in bind(tag, extent) #exchange the position

thread_x = thread_axis("threadIdx.x") #declare it first
for tx in bind(thread_x, extent) #use the declaration when binding
````

*NOTE*: A semantic different from Python:
````
for i in range(5):
    sum = 0
    for j in range(5):
        sum += a[i][j]
    b[i] = sum
#You can NEVER use sum here
````
 
Example
=========
Here is roughly a whole example:
````Python
@tvm.hybrid.script
def foo(a, b, c):
    for i in serial(a.shape[0]):
        for j in serial(b.shape[0]):
            c[i, j] = a[i] * b[j]

a = tvm.placeholder((100, ), name='a')
b = tvm.placeholder((99, ), name='b')
c = tvm.placeholder((100, 99), name='c')
ir, _ = tvm.hybrid.parse(foo, [a, b, c]) #ir is the ir node, _ is the parser itself
op = foo(a, b, c) #So far it is same as calling parse, but we are gonna change it to returning a op
sch = tvm.create_schedule(op)
jo, ji = sch.split(j, 4)
sch.vectorize(ji)
````

**Comment by were** [comment]
@tqchen Gather some people to discuss!

**Comment by tqchen** [comment]
@merrymercy @eqy @kevinthesun @Laurawly @xqdan @ZihengJiang  Please read the hybrid script spec and participate the RFC discussion, we want to discuss the following questions:

## What is the preferred way of specifying bind thread syntax
1) explicit bind
```
for tx in bind("threadIdx.x", extent):
   pass
```
2) code mixing, similar to TVM convention
```
thread_x = thread_axis("thread", (0, extent))
for tx in bind(thread_x):
    pass
```

## What is the preferred way of naming the annotated loops
Currently, keywords are: unrolled, vectorized, serial, parallel.

**Comment by xqdan** [comment]
1, bind thread syntax: 
-  explicit bind is better for its simplicity

2, naming the annotated loops: 
- can we make serial as default so we can get ride of serial, 
- we may use uniform style, with or without -ed, like unroll vectorize parallel

**Comment by xqdan** [comment]
A new Features to discuss, 
For some complex ops, they may need STL in cuda c++, so can we have containers in python front end and then tvm lowers this into STL?

**Comment by were** [comment]
@eqy This frontend is to write some preliminary IR code. Because we are using conventional imperative language, we do somehow abandon the halide-style decouple.

@xqdan the -ed thing is to be consistent to `For` class in the `stmt.py`.

@nhynes Thank you for ur suggestion. Later I will support the `*` thing and add some interfaces for users to register their own intrinsics in the decorator.

**Comment by tqchen** [comment]
thanks for all the helpful discussions, I would suggest the following steps move forward @were 

- [ ] Summarize the design decision, language, keyword, examples descriptions in docs/dev/hybrid_script.md (reuse what we have in this issue)
- [ ] Also cross pasting the issue in here
- [ ] Update the PR to support the discussed feature, up to the parse function
- [ ] Write a tutorial on how to use hybrid script under tutorials
- [ ] Support generating of op in a later part of the PR, the first step can redirect to extern op
- [ ] Support scheduling of outer loop nest structures.
- [ ] Write a blogpost introducing this feature.

**Comment by tqchen** [comment]
This issue can be closed as #1251 is merged. @were let us open another issues for the next stage working  items
