### ISSUE TITLE
[RELAY][DOCS] Relay Documentation Sprint

### ISSUE THREAD

**Issue by jroesch** [dmlc/tvm#2212]
Now that we are working towards a beta version of Relay and have stabilized many of the APIs it would be good to sprint on completing a first version of the documentation for the APIs and IR.

We have a couple pieces of docs:

- [x] Tianqi's tutorial (see #2185)
- [x] API Docs (see #1750, @jroesch is in process of updating it) 
- [x] Language Reference (will be derived from #1750).
    - [x] Add introduction to Relay to language reference.
    - [x] Add language reference for the expression language.
    - [x] Add language reference on type system.
    - [x] Incorporate the operator index.
    - [x] Add list of optimization and brief descriptions.
- [ ] Developer's guide to Relay
   - [ ] Add introduction
   - [ ] Explain System Arch.
   - [ ] Explain type inference
   - [ ] Pass architecture
   - [ ] Technical cover of optimizations
   - [ ] Platforms 
  - [ ] Port (https://github.com/dmlc/tvm/pull/2206)

Will continue to update with more fine grained goals as we open PRs.
