### ISSUE TITLE
TVM 0.1 Release Roadmap 

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#275]
Thanks all for pushing hard toward the release. We plan to make the repo public on Thursday, it is two days behind our original plan but hopefully we get most pieces here. I will keep editing the issue to as we have more updates, the checklist will go into the release note.

## Check List
- Language runtime
    - [x] python
    - [x] javascript
    - [x] java
    - [x] c++
- Backend
    - [x] arm, x86
    - [x] javascript, wasm
    - [x] CUDA
    - [x] opencl
    - [x] Metal
- DNN Library integration
    - [x] nnpack fc
    - [x] nnpack conv
    - [x] CuDNN
    - [ ] MPS
- RPC  runtime
    - [x] Normal RPC
    - [x] RPC Proxy
    - [x] Websocket RPC
    - [ ] Android RPC
    - [x] iOS RPC
- TOPI operator pipeline python
    - [x] Convolution
    - [x] Depthwise convolution
    - [x] GEMM
    - [x] Broadcast and reduction
- TOPI operator pipeline in C++
    - [x] Convolution
    - [x] Depthwise
    - [x] Broadcast 
    - [ ] reduction
- Rough perf of the TOPI GPU pipeline
    - [x] GPU GEMM 
    - [x] GPU depthwise-conv
    - [x] GPU conv2d, batch=64
    - [x] GPU conv2d, batch=1 
    - [x] GPU bcast and reduction
- Rough pref of TOPI CPU pipeline
     - [x] CPU GEMM
     - [ ] CPU conv2d
     - [ ] CPU depthwise-conv
     - [ ] CPU bcast and reduction
- End to end graph executors
    - [x] Basic graph lowering framework
    - [x] NNVM Graph runtime
    - [ ] Resnet pipeline CPU version
    - [ ] Resnet pipeline raspi

**Comment by tqchen** [comment]
close this for now as the release note as been updated

**Comment by tqchen** [comment]
Roadmap for v0.2 https://github.com/dmlc/tvm/issues/349
